### ISSUE TITLE
Not working in Tensorflow 1.2.1?

### ISSUE THREAD

**Issue by ieee8023** [WeidiXie/cell_counting_v2#5]
Should I fix my system or fix the code?

```
$ python train.py
Using TensorFlow backend.
------------------------------
Creating and compiling the fully convolutional regression networks.
------------------------------
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    train_(base_path)
  File "train.py", line 77, in train_
    model = buildModel_U_net(input_dim = (256,256,3))
  File "/data/lisa/exp/cohenjos/workspace/cell_counting_v2/model.py", line 167, in buildModel_U_net
    act_ = U_net_base (input_, nb_filter = 64 )
  File "/data/lisa/exp/cohenjos/workspace/cell_counting_v2/model.py", line 127, in U_net_base
    up4 = merge([UpSampling2D(size=(2, 2))(block4), block3], mode='concat', concat_axis=-1)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 1680, in merge
    name=name)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 1301, in __init__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 635, in add_inbound_n
ode
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 172, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/u/cohenjos/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 1394, in call
    return K.concatenate(inputs, axis=self.concat_axis)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1427, in c
oncatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/u/cohenjos/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1043, in co
ncat
    dtype=dtypes.int32).get_shape(
  File "/u/cohenjos/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 676, in con
vert_to_tensor
    as_ref=False)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 741, in int
ernal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113
, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102
, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/u/cohenjos/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 374
, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/u/cohenjos/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302
, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

**Comment by WeidiXie** [comment]
Hi, 

I think this is due to the tensorflow update..... 
they have changed the order of parameters, I guess.
